# 7 Deploy after clearing cache. 
inspecode:
  experimental:
    cache: true
    incremental: true
    runtime:
      go: 1.11
    ignore:
      - '**/bindata.go'
      - 'vendor/'

  thresholds:
    complexity: 15

  goimports:
  - auto-fix: true
    ignore: '**/testdata'
    thresholds:
      num-issues: 47
  - input: '**/testdata'
    